### ISSUE TITLE
It's not clear what this repository is about

### ISSUE THREAD

**Issue by X-Ryl669** [christiaangoossens/hass-oidc-auth#1]
I know it's a WIP repository, but I don't understand what problem it's trying to solve.

If you're trying to skip the HASS login page (typically by redirecting to some SSO server like Authelia), then there's no way this can work since redirection must happen before the HTTP request's body is started and it's inside the body that the authentication API requests are triggered. Even with a javascript hack trying to change `window.location` to the SSO's login page, this will create a clunky user experience, where the browser load the (heavy) login page and then throw it away to load the SSO login page.

Due to the code size of HASS, I'm not sure a solution like using a reverse proxy to HASS from Authelia is a good solution either (and again, it's clunky for any automation like the mobile app or any application that's not expecting this lengthy redirect dance).

If I understand correctly what was implemented [here](https://github.com/BeryJu/hass-auth-header/blob/master/custom_components/auth_header/headers.py), and HASS source code [here](https://github.com/home-assistant/core/blob/dev/homeassistant/auth/providers/homeassistant.py) I think this isn't the right place to act. 

Typically, I think it would be better if authentication would be completely bypassed (that is, by changing HASS core behavior to an "Always authenticated" auth provider that would simply ignore authentication if some internal + external header are present) so that the login page is never requested at all.

Then the code would hook into the [AuthStore](https://github.com/home-assistant/core/blob/dev/homeassistant/auth/auth_store.py#L34) class instead so it can request the OIDC provider here instead (like Authelia or any other) for the user's information, but from the server side. In case of failure (bad authentication, expired token, etc...), it would actually redirect the client (browser/mobile app) to the defined callback before any view is actually generated, so it's a real SSO process.

A mobile app or any other application that isn't expecting this redirect dance can then be bypassed since the required header won't be here, the default HASS login will trigger.

So the process would be something like:
```
Web: [SSO proxy] => [NGINX ] => [HASS] 
           /\   "X-InternalHeader: present"    

Mobile: [NGINX] => [HASS]
             "No specific header present"
```

Inside HASS, the pseudo code would do:
```
AlwaysValidAuthProvider:
   if (X-InternalHeader  present) => change AuthStore to OIDCAuthStore
  else => forward to the next AuthProvider

OIDCAuthStore:
   // From configuration, connect on the OIDC provider to check if a valid token is available. 
   // If no token found, redirect client to Authentication page (next try should succeed then)
   // Else token is valid, extract information from OIDC
```

**Comment by christiaangoossens** [comment]
Hi @X-Ryl669, I don't know why I missed a notification about this, but I will answer it now regardless. Please review https://community.home-assistant.io/t/open-letter-for-improving-home-assistants-authentication-system-oidc-sso/494223 first for the background on why we would like SSO in Home Assistant.

Specifically, this repository rejects the current solutions that proxy Home Assistant with header auth, as it does not work properly on mobile (old webviews being used) and is always a temporary solution until SSO is implemented regardless.

Bypassing the Home Assistant screens is not the problem at hand here, I wouldn't mind if they stay. The main issue is that there seems to be no option in the codebase to direct the user to go to any external page when your auth source is started/clicked upon. Home Assistant always assumes that your auth source just shows an input form, not that it redirects (browser) or shows a Chrome Custom Tab (Android) or Safari view (iOS).

I think it is possible to implement OIDC into Home Assistant regardless, possibly by having the user go to a specific URL in their preferred browser and obtaining a digit token (6 or 8 digits) that they can input into the form that Home Assistant shows for this provider. That would show the concept and allow those more familiar with Home Assistant's code base to complete the user flow instead (together with the mobile devs, as you cannot just redirect on mobile). However, due to the hostility faced from the project and my time constraints, I have not attempted this yet.

**Comment by christiaangoossens** [comment]
@X-Ryl669 

> I think it is possible to implement OIDC into Home Assistant regardless, possibly by having the user go to a specific URL in their preferred browser, completing the usual OIDC flow and at the end obtaining a digit token (6 or 8 digits) that they can input into the form that Home Assistant shows for this provider (which is temporarily stored on the Home Assistant db). That would show the concept and allow those more familiar with Home Assistant's code base to complete the user flow instead (together with the mobile devs, as you cannot just redirect on mobile).

I decided to just put my money where my mouth is and implement this solution in a very basic form as a proof of concept. If you want, you can test it as well.

**Comment by X-Ryl669** [comment]
Sorry for the delay and not keeping you up with this. I've used Authelia and hass header login plugin to do SSO what I wanted (see [here](https://blog.cyril.by/en/software/single-sign-on/example-sso-with-authelia-and-home-assistant)). 

The actual workflow is:
1. You connect to your HA instance.
2. The HA plugin detects you don't have the appropriate cookie, it redirects to the Authelia's SSO page (you can customize it if you want, as I did)
3. Once you're logged to Authelia page, you're redirected to the HA instance and you'll have the Authelia's cookie, so it'll be accepted
4. The HA login page is thus skipped and you directly go to the interface.

It doesn't work on mobile app, since the webview isn't allowed to escape the domain it's built on, yet, there's a workaround (see the linked website). 

If your implementation can do OIDC, and the mobile app is modified to accept this, it can probably be a one size fits all solution.

**Comment by christiaangoossens** [comment]
@X-Ryl669 For a long time, the header auth solution was the best implementation. It's however always intended as a temporary fix for apps that don't support native OIDC.

The current pre-alpha build here supports both desktop and mobile HA right now, without any fixes for HA. It's not the prettiest, but we'll work on that. It doesn't need any proxy changes from the standard setup, just install this through HACS and setup the config.

You are welcome to test it with Authelia and report your findings, I expect you will need to configure different id_token claims for username and groups (which is my next TODO).

I am planning to test it myself too with at least Keycloak, Authentik and Authelia.
